/*
 * Placeholder fsdata.c - generated by web build process.
 * This minimal file allows firmware compilation without the web configurator.
 * Run a full build (without SKIP_WEBBUILD) to generate the real web UI data.
 */
#include "fsdata.h"

#define file_NULL (struct fsdata_file *) NULL

#ifndef FS_FILE_FLAGS_HEADER_INCLUDED
#define FS_FILE_FLAGS_HEADER_INCLUDED 1
#endif

static const unsigned char data__index_html_name[] = "/index.html";
static const unsigned char data__index_html[] = 
    "HTTP/1.0 200 OK\r\n"
    "Content-Type: text/html\r\n\r\n"
    "<html><body><h1>GP2040-CE</h1><p>Web build not included. Rebuild with SKIP_WEBBUILD=FALSE.</p></body></html>";

const struct fsdata_file file__index_html[] = {
    {
        file_NULL,
        data__index_html_name,
        data__index_html,
        sizeof(data__index_html) - 1,
        FS_FILE_FLAGS_HEADER_INCLUDED,
    }
};

#define FS_ROOT file__index_html
#define FS_NUMFILES 1
